import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomeFoodie from "@/components/main-background/homeFoodie";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Foodie Food",
  description: "Generated by Foodies",
icons:{
  icon:['/image/favicon.ico']
}
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <HomeFoodie/>
        {children}
      
      </body>
    </html>
  );
}
